---
- name: Deploy to Dev environment using Meraki API
  hosts: localhost
  gather_facts: false

  vars:
    meraki_api_key: "{{ lookup('env', 'MERAKI_API_KEY') }}"
    org_id: "{{ lookup('env', 'ORG_ID') }}"
    dev_network_id: "{{ lookup('env', 'DEV_NETWORK_ID') }}"

  tasks:
    - name: Debug Variables
      debug:
        var:
          - meraki_api_key
          - org_id
          - dev_network_id

    - name: Create Dev network
      uri:
        url: "https://api.meraki.com/api/v1/organizations/{{ org_id }}/networks"
        method: POST
        headers:
          Content-Type: "application/json"
          X-Cisco-Meraki-API-Key: "{{ meraki_api_key }}"
        body_format: json
        body:
          name: "Dev Network"
          type: "appliance"  # Set the type to "appliance" for Meraki MX Firewalls
          timeZone: "America/New_York"
        status_code: 201
      register: dev_network_response

    - name: Print Dev network creation status
      debug:
        var: dev_network_response.json

    # Add the rest of your tasks...

    - name: Print success message
      debug:
        msg: "Dev deployment successful!"
