---
- name: Deploy to Dev environment using Meraki API
  hosts: localhost
  gather_facts: false

  vars:
    meraki_api_key: "{{ lookup('env', 'MERAKI_API_KEY') }}"
    org_id: "{{ lookup('env', 'ORG_ID') }}"
    dev_network_id: "Nashville_TN_Branch"  # Manually set the value

  tasks:
    - name: Debug Variables
      debug:
        var:
          - "meraki_api_key"
          - "org_id"
          - "dev_network_id"
      vars:
        meraki_api_key: "{{ lookup('env', 'MERAKI_API_KEY') }}"
        org_id: "{{ lookup('env', 'ORG_ID') }}"
        dev_network_id: "Nashville_TN_Branch"  # Manually set the value

    - name: Create Dev network
      debug:
        var:
          - "url"
          - "headers"
      vars:
        url: "https://api.meraki.com/api/v1/organizations/{{ org_id }}/networks"
        headers:
          Content-Type: "application/json"
          X-Cisco-Meraki-API-Key: "{{ meraki_api_key }}"

    # Continue with the rest of your tasks...
    # ...

    - name: Print success message
      debug:
        msg: "Dev deployment successful!"
