version: 2.1

jobs:
  fetch-meraki-networks:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install requests
      
      - run:
          name: Create Meraki Networks
          command: |
            python test.py
            #python .github/scripts/test.py

      - run:
          name: Fetch Meraki Networks
          command: |
            python .github/scripts/fetch_meraki_networks.py
            #python .github/scripts/test.py


workflows:
  my-workflow:
    jobs:
      - fetch-meraki-networks:
          context:
            - meraki_stuff