version: 2.1

jobs:
  fetch-meraki-networks:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install requests
            pip install meraki
      
      # - run:
      #     name: Create Meraki Networks
      #     command: |
      #       python test.py
      #       #python test.py

      - run:
          name: Fetch Meraki Networks
          command: |
            # python fetch_meraki_networks.py
            #python .github/scripts/test.py
            python create_vlan.py


workflows:
  my-workflow:
    jobs:
      - fetch-meraki-networks:
          context:
            - meraki_stuff