version: 2.1

jobs:
  fetch-meraki-networks:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install requests

      - run:
          name: Fetch Meraki Networks
          command: |
            #python .github/scripts/fetch_meraki_networks.py
            python .github/scripts/test.py
          # environment:
          #   MERAKI_API_KEY: $MERAKI_API_KEY
          #   ORG_ID: $ORG_ID


workflows:
  my-workflow:
    jobs:
      - fetch-meraki-networks:
          context:
            - meraki_stuff