version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install requests
            pip install meraki
            pip install --upgrade meraki

  deploy_dev_staging:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install requests
            pip install meraki
            pip install --upgrade meraki

      - run:
          name: Show Networks
          command: |
            python show/show_networks.py
            python -c "print('~' * 40)"

      - run:
          name: Create Networks
          command: |
            python create_staging_network/las_vegas_staging_network/las_vegas_network.py
            python -c "print('~' * 40)"

      - run:
          name: Show Networks
          command: |
            python show/show_networks.py
            python -c "print('~' * 40)"

      - run:
          name: Create VLANS & DHCP
          command: |
            python create_staging_vlans_dhcp/las_vegas_staging_vlans_dhcp/las_vegas_staging_vlans_dhcp.py
            python -c "print('~' * 40)"
            
      - run:
          name: Show VLANS & DHCP
          command: |
            python show/show_vlans_dhcp.py
            python -c "print('~' * 40)"

      - persist_to_workspace:
          root: .
          paths:
            - created_network_id.txt



  delete_staging_env:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install requests
            pip install meraki
            pip install --upgrade meraki

      - attach_workspace:
          at: /workspace/project/create_staging_network

      - run:
          name: Show Networks
          command: |
            python show/show_networks.py
            python -c "print('~' * 40)"
            
      - run:
          name: Show VLANS & DHCP
          command: |
            python show/show_vlans_dhcp.py
            python -c "print('~' * 40)"

      - run:
          name: Delete VLANS & DHCP
          command: |
            python delete_staging_vlans_dhcp/delete_vlans_dhcp.py
            python -c "print('~' * 40)"

      - run:
          name: Show VLANS & DHCP
          command: |
            python show/show_vlans_dhcp.py
            python -c "print('~' * 40)"

      - run:
          name: Delete Networks
          command: |
            python delete_staging_network/delete_network.py
            python -c "print('~' * 40)"

      - run:
          name: Show Networks
          command: |
            python show/show_networks.py
            python -c "print('~' * 40)"

  deploy_prod:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install requests
            pip install meraki
            pip install --upgrade meraki

      - run:
          name: Create Networks
          command: |
            python create_production_network/las_vegas_prod_network/las_vegas_network.py
            python -c "print('~' * 40)"
      
      - run:
          name: Show Networks
          command: |
            python show/show_networks.py
            python -c "print('~' * 40)"

      - run:
          name: Create VLANS & DHCP
          command: |
            python create_production_vlans_dhcp/las_vegas_prod_vlans_dhcp/las_vegas_prod_vlans_dhcp.py
            python -c "print('~' * 40)"

      - run:
          name: Show VLANS & DHCP
          command: |
            python show/show_vlans_dhcp.py
            python -c "print('~' * 40)"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - hold:
          type: approval
          requires:
            - build

      - hold_delete:
          type: approval
          requires:
            - deploy_dev_staging

      - build:
          context:
            - meraki_stuff

      - deploy_dev_staging:
          context:
            - meraki_stuff
          requires:
            - hold
          filters:
            branches:
              ignore: main  # Ignore the MAIN branch, trigger for other branches

      - delete_staging_env:
          context:
            - meraki_stuff
          requires:
            - hold_delete
          filters:
            branches:
              ignore: main  # Ignore the MAIN branch, trigger for other branches

      - deploy_prod:
          requires:
            - hold
          context:
            - meraki_stuff
          filters:
            branches:
              only: main  # Trigger only for the MAIN branch
