version: 2.1

jobs:

  build:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install requests
            pip install meraki

  deploy_dev_staging:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      # Add steps to deploy to DEV_STAGING
      # This job will be triggered for branches other than MAIN
      - run:
          name: Install Dependencies
          command: |
            pip install requests
            pip install meraki

      - run:
          name: Show Networks
          command: |
            python show/show_networks.py
            python -c "print('~' * 40)"

      # - run:
      #     name: Create Networks
      #     command: |
      #       python create_network/create_network.py
      #       python -c "print('~' * 40)"

      # - run:
      #     name: Show Networks
      #     command: |
      #       python show/show_networks.py
      #       python -c "print('~' * 40)"

      - run:
          name: Delete Networks
          command: |
            python delete_network/delete_network.py
            python -c "print('~' * 40)"

      - run:
          name: Show Networks
          command: |
            python show_networks/show_networks.py
            python -c "print('~' * 40)"
            
      - run:
          name: Show VLANS & DHCP
          command: |
            python show_networks/show_vlans_dhcp.py
            python -c "print('~' * 40)"
      
      # - run:
      #     name: Delete VLANS & DHCP
      #     command: |
      #       python delete_networks.py
      #       python -c "print('~' * 40)"

      # - run:
      #     name: Show VLANS & DHCP
      #     command: |
      #       python vlans_dhcp.py
      #       python -c "print('~' * 40)"
      
      # - run:
      #     name: Create VLANS & DHCP
      #     command: |
      #       python create_vlan.py
      #       python -c "print('~' * 40)"

      # - run:
      #     name: Show VLANS & DHCP
      #     command: |
      #       python vlans_dhcp.py
      #       python -c "print('~' * 40)"

  deploy_prod:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      # Add steps to deploy to PROD
      # This job will be triggered for the MAIN branch
      - run:
          name: Install Dependencies
          command: |
            pip install requests
            pip install meraki
      - run:
          name: Create VLANS
          command: |
            # python fetch_meraki_networks.py
            #python .github/scripts/test.py
            python show_networks.py
            # python create_vlan.py


workflows:
  version: 2
  build_and_deploy:
    jobs:
      
      - hold:
          type: approval
          requires:
            - build

      - build:
          context:
            - meraki_stuff

      - deploy_dev_staging:
          context:
            - meraki_stuff
          requires:
            - hold
          filters:
            branches:
              ignore: main  # Ignore the MAIN branch, trigger for other branches

      - deploy_prod:
          requires:
            - hold
          context:
            - meraki_stuff
          filters:
            branches:
              only: main  # Trigger only for the MAIN branch

# workflows:
#   my-workflow:
#     jobs:
#       - build:
#           context:
#             - meraki_stuff